<?php declare(strict_types=1);

namespace Becklyn\SchemaOrg\Schema;

use Becklyn\SchemaOrg\Data\SchemaOrgDataInterface;

interface MetaDataNormalizer
{
    /**
     * The Schema.org type that is generated by this normalizer.
     */
    public function getSchemaType () : string;


    /**
     * The underlying internal Schema.org entity class that is used to generate the JSON-LD schema.
     */
    public function getEntityClass () : string;


    /**
     * Normalizes the Schema.org data structure into their JSON-LD representation.
     *
     * If no schema can be generated, return `null`.
     */
    public function normalize (MetaDataNormalizerRegistry $registry, SchemaOrgDataInterface $entity, ?string $usage = null, array $context = [], bool $isNested = false) : ?array;
}
